services:
  db:
    restart: always
    image: docker.io/library/postgres:17.0-alpine3.20
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: /run/secrets/db_name
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
    - db_name
    - db_user
    - db_password
  web:
    restart: always
    build: .
    command:
      - /bin/sh
      - -c
      - |
        . /run/secrets/email_env
        python manage.py makemigrations --no-input
        python manage.py migrate --no-input
        python manage.py migrate --run-syncdb --no-input
        python manage.py collectstatic --no-input
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: /run/secrets/django_secret
      DJANGO_DB_NAME: /run/secrets/db_name
      DJANGO_DB_USER: /run/secrets/db_user
      DJANGO_DB_PASSWORD: /run/secrets/db_password
      DJANGO_DB_HOST: db
      DJANGO_HOST: "*"
    secrets:
    - db_name
    - db_user
    - db_password
    - django_secret
    depends_on:
      - db

secrets:
  db_name:
    file: /root/secrets/db_name.txt
  db_user:
    file: /root/secrets/db_user.txt
  db_password:
    file: /root/secrets/db_password.txt
  django_secret:
    file: /root/secrets/django_secret.txt
  email_env:
    file: /root/secrets/email.env
